//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryPublishingHouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Publication()
        {
            this.Authors = new HashSet<Author>();
        }
    
        public int IdPublication { get; set; }
        public string PublicationName { get; set; }
        public Nullable<int> IdUDK { get; set; }
        public Nullable<int> IdMagazine { get; set; }
        public Nullable<int> IdType { get; set; }
        public Nullable<int> RegistrationNum { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
    
        public virtual Magazine Magazine { get; set; }
        public virtual PublicationType PublicationType { get; set; }
        public virtual UDK UDK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Author> Authors { get; set; }
    }
}
